### ISSUE TITLE
Question: I can't follow up with README.md to decrypt the JSON file

### ISSUE THREAD

**Issue by Remexllee** [GoogleChrome/lighthouse-keeper#22]
Hi, I am following with README to decrypt the service account and memcache JSON files
when I set a simple passphrase, I got error as below:

-------------------------------------------
enter aes-256-cbc decryption password:
bad decrypt
4521469548:error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/crypto/evp/evp_enc.c:533:

I would like to know is this passphrase connectted with other account or just simple passphrase for my local.

**Comment by robdodson** [comment]
Hi @Remexllee,

I'm not the original author of this project but it seems like you would need to create a new service account with your own google cloud project and then generate your own credentials for firestore and redis.

**Comment by Remexllee** [comment]
Hi @robdodson 
Thanks for the comment, I will have try and let you know whether it works.
